---
- name: "Set hostname to {{ hostname }}"
  hostname:
    name: "{{ hostname }}"

- name: "Set timezone to {{ timezone }}"
  community.general.timezone:
    name: "{{ timezone }}"
  become: true

- name: Install packages
  become: yes
  package:
    name:
      - git
      - avahi-daemon
      - libnss-mdns
    state: latest

- name: Start Avahi deamon for mDNS advertisement
  systemd:
    state: restarted
    name: avahi-daemon
    enabled: true
